#ifndef LWCOMSTREAMER_GLOBAL_H
#define LWCOMSTREAMER_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(LWCOMSTREAMER_LIBRARY)
#  define LWCOMSTREAMERSHARED_EXPORT Q_DECL_EXPORT
#else
#  define LWCOMSTREAMERSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // LWCOMSTREAMER_GLOBAL_H
